-- Logs data model for cloud sync
-- Tables:
-- 1) daily_logs
-- 2) saved_meals
-- 3) supplement_library

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  log_date date not null,
  weight_value numeric(6,2),
  weight_unit text not null default 'kg' check (weight_unit in ('kg', 'lbs')),
  water_amount numeric(8,2),
  water_unit text not null default 'ml' check (water_unit in ('ml', 'liters')),
  meals jsonb not null default '[]'::jsonb,
  supplements_taken jsonb not null default '[]'::jsonb,
  extra_activities jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, log_date)
);

create table if not exists public.saved_meals (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  name text not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

create unique index if not exists saved_meals_user_name_unique
  on public.saved_meals (user_id, lower(name));

create table if not exists public.supplement_library (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists supplement_library_user_name_unique
  on public.supplement_library (user_id, lower(name));

create index if not exists daily_logs_user_date_idx
  on public.daily_logs (user_id, log_date desc);

create index if not exists saved_meals_user_idx
  on public.saved_meals (user_id);

create index if not exists supplement_library_user_idx
  on public.supplement_library (user_id);

create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_daily_logs_updated_at on public.daily_logs;
create trigger trg_daily_logs_updated_at
before update on public.daily_logs
for each row execute function public.set_updated_at_timestamp();
