/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: '#34D399', // soft green
        secondary: '#F3F4F6', // light grey
        accent: '#10B981', // darker green
      },
      fontFamily: {
        sans: ['Helvetica', 'Arial', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

// // autogenerated file created by installing tailwind react on vscode , haven't modified this file